version: 0.0.1

networks:
  my_net:

services:
  mysql:
    image: mysql:latest
    container_name: just_dab_sql
    ports:
      - 3333:3306
    networks:
      - my_net
    volumes:
      - data:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=just_dab_db

  backend:
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: just_dab_back
    ports:
      - 8081:8080
    networks:
      - my_net
    environment:
      - DATABASE_URL=jdbc:mysql://just_dab_sql:3306/just_dab_db
      - DATABASE_PASSWORD=password

volumes:
  data: